
#Alle Konfigurationen zu Kernfunktionen des Spiels
[gameplay]
	#Anzahl der Erstbürger. [Standard: 4, min: 1, max: 10]
	#Range: 1 ~ 10
	initialcitizenamount = 4
	#Sollen Spieler in der Lage sein, unendlich viele Vorratslager / -schiffe zu platzieren? [Standard: false]
	allowinfinitesupplychests = false
	#Dürfen Spieler ihre Kolonie verlassen, um einfach eine neue zu erstellen? Achtung: das ist buggy! [Standard: false]
	allowinfinitecolonies = false
	#Sollten Kolonien in anderen Dimensionen erlaubt sein? [Standard: true]
	allowotherdimcolonies = true
	#Maximale Einwohner in einer Kolonie. [Standard: 250, min: 100, max: 500]
	#Range: 100 ~ 500
	maxcitizenpercolony = 250
	#Sollen Funktionen, die in der Entwicklung sind, aktiv sein (könnten Fehlerhaft sein)? [Standard: false]
	enableindevelopmentfeatures = false
	#Sollen die Namensschilder der Einwohner gerendert werden? [Standard: true]
	alwaysrendernametag = true
	#Sollen Arbeiter arbeiten, während es regnet? [Standard: false]
	workersalwaysworkinrain = false
	#Soll spezieller Feiertagsinhalt angezeigt werden? [Standard: true]
	holidayfeatures = true
	#Chance für den Miner, Erze zu bekommen wenn er Bruchstein oder Stein abbaut (kann per Datapack auf andere Materialien ausgeweitet werden). In %. (Zum Ändern, welche Erze der Miner finden kann, siehe "Liste von Bonus Erzen") [Standard: 1, min: 0, max: 100]
	#Range: 0 ~ 100
	luckyblockchance = 1
	#Das Mindestlevel des Rathauses, um das Teleportieren zu anderen Kolonien zu erlauben. [Standard: 3, min: 0, max: 5]
	#Range: 0 ~ 5
	minthleveltoteleport = 3
	#Essensverbrauch Multiplikator. [Standard: 1,000000, min: 0,100000, max: 100,000000]
	#Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#Wie gewöhnlich sind Krankheiten. 1 = Sehr gewöhnlich, 100 = Extrem selten. [Standard: 5, min: 1, max: 100]
	#Range: 1 ~ 100
	diseasemodifier = 5
	#Wenn ein Teil der Kolonie von einem Besitzer/Offizier geladen wird, soll die Kolonie geladen bleiben? (Lege mit der Option "Kolonie-Chunk-Ladestrenge" fest, wie viele Chunks geladen werden.) [Standard: true]
	forceloadcolony = true
	#Bestimme, wie lange ein Chunk geladen bleibt, nachdem der Spieler die Welt verlassen hat. Wird durch Neustart zurückgesetzt. Standard: 10 Min [Standard: 10, min: 1, max: 1440]
	#Range: 1 ~ 1440
	loadtime = 10
	#Hiermit wird gesteuert, wie viele Chunks mit der Option "Chunkladen der Kolonie" geladen werden. Je höher dieser Wert ist, desto weniger Chunks werden geladen. (Die innersten Chunks werden zuerst geladen.) 1 = alle beanspruchten Chunks laden. [Standard: 3, min: 1, max: 15]
	#Range: 1 ~ 15
	colonyloadstrictness = 3
	#Maximale Baumstamm-Anzahl bei einem Baum nach denen der Förster bei seiner Suche sucht. [Standard: 400, min: 1, max: 1000]
	#Range: 1 ~ 1000
	maxtreesize = 400
	#Deaktiviert Einschränkungen beim Platzieren des Nachschublagers, gedacht für Skyworld und ähnliches [Standard: false]
	nosupplyplacementrestrictions = false
	#Plünderer werden im Himmel erscheinen, wenn aktiviert [Standard: false]
	skyraiders = false

#Alle Konfigurationen im Zusammenhang mit dem Forschungssystem
[research]
	#Erlaubt automatischen und (fast) sofortigen Abschluss von Forschung für Spieler im Creative Modus. Wenn abgeschaltet, können Spieler im Creative Modus Forschung beginnen, diese hat dann die Standard Fortschrittsgeschwindigkeit. [Standard: true]
	researchcreativecompletion = true
	#Erhöht die Anzahl an Informationen, die mit Forschungs-Datapaketen zusammenhängen, die während des Ladens protokolliert werden. [Standard: false]
	researchdebuglog = false
	#Eine Liste von Gegenständen, die den Spielern beim Rückgängigmachen einer bereits abgeschlossenen Forschung in Rechnung gestellt werden müssen. 
	researchresetcost = ["minecolonies:ancienttome:1"]

#Alle Konfigurationen bezüglich der Befehle von MineColonies
[commands]
	#Sollte Spielern erlaubt sein den "/mc rtp" Befehl zu nutzen? [Standard: false]
	canplayerusertpcommand = false
	#Soll Spielern erlaubt sein den "/mc colony teleport" Befehl zu nutzen? [Standard: false]
	canplayerusecolonytpcommand = false
	#Sollte Spielern erlaubt sein sich zu Verbündeten Kolonien zu teleportieren? [Standard: true]
	canplayeruseallytownhallteleport = true
	#Soll Spielern erlaubt sein den "/mc home" Befehl zu nutzen? Anmerkung: Nur Inhaber der Kolonie können diesen Befehl nutzen. [Standard: false]
	canplayerusehometpcommand = false
	#Soll Spielern erlaubt sein den "/mc colony info" Befehl zu nutzen? [Standard: true]
	canplayeruseshowcolonyinfocommand = true
	#Soll Spielern erlaubt sein den "/mc citizens kill" Befehl zu nutzen? [Standard: false]
	canplayerusekillcitizenscommand = false
	#Soll Spielern erlaubt sein den "/mc colony addOfficer" Befehl zu nutzen? [Standard: true]
	canplayeruseaddofficercommand = true
	#Soll Spielern erlaubt sein den "/mc colony delete" Befehl zu nutzen? [Standard: false]
	canplayerusedeletecolonycommand = false
	#Soll es Spielern erlaubt sein, den Befehl /mc colony requestsystem-reset zu verwenden? [Standard: false]
	canplayeruseresetcommand = false

#Alle Konfigurationen im Zusammenhang mit Kolonieansprüchen
[claims]
	#Maximaler Anspruchsbereich für eine Kolonie. Dies ist der Radius, gemessen in Chunks. [Standard: 20, min: 1, max: 250]
	#Range: 1 ~ 250
	maxColonySize = 20
	#Die Minimale Distanz (in Chunks) zwischen Kolonien. [Standard: 8, min: 1, max: 200]
	#Range: 1 ~ 200
	minColonyDistance = 8
	#Initialer Anspruchsbereich für eine Kolonie. Dies ist der Radius, gemessen in Chunks. [Standard: 4, min: 1, max: 15]
	#Range: 1 ~ 15
	initialColonySize = 4
	#Maximale Entfernung (in Blöcken) vom Weltspawn für eine Kolonie. [Standard: 30000, min: 1000, max: 2147483647]
	#Range: > 1000
	maxdistancefromworldspawn = 30000
	#Minimale Entfernung (in Blöcken) vom Weltspawn für eine Kolonie. [Standard: 0, min: 0, max: 1000]
	#Range: 0 ~ 1000
	mindistancefromworldspawn = 0

#Alle Konfigurationen bezüglich des Kampfsystems von MineColonies
[combat]
	#minecolonies.config.dobarbariansspawn.comment [Standard: true]
	dobarbariansspawn = true
	#minecolonies.config.barbarianhordedifficulty.comment [Standard: 5, min: 0, max: 10]
	#Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#minecolonies.config.maxbarbariansize.comment [Standard: 80, min: 6, max: 400]
	#Range: 6 ~ 400
	maxBarbarianSize = 80
	#minecolonies.config.dobarbariansbreakthroughwalls.comment [Standard: true]
	dobarbariansbreakthroughwalls = true
	#Die durchschnittliche Anzahl an Nächten zwischen Überfällen. [Standard: 14, min: 1, max: 50]
	#Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 14
	#Die minimale Anzahl an Nächten zwischen Überfällen. [Standard: 10, min: 1, max: 30]
	#Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 10
	#Sollen Monster Einwohner angreifen? [Standard: true]
	mobattackcitizens = true
	#minecolonies.config.shouldraiderbreakdoors.comment [Standard: true]
	shouldraiderbreakdoors = true
	#minecolonies.config.guarddamagemultiplier.comment [Standard: 1,000000, min: 0,100000, max: 15,000000]
	#Range: 0.1 ~ 15.0
	guardDamageMultiplier = 1.0
	#Lebenmultiplikator für alle Wachen. [Standard: 1,000000, min: 0,100000, max: 5,000000]
	#Range: 0.1 ~ 5.0
	guardhealthmult = 1.0
	#Aktiviere Minecolonies PVP Modus (Achtung Kolonien können unter bestimmten Umständen gegrieft und zerstört werden). [Standard: false]
	pvp_mode = true

#Alle Berechtigungseinstellungen
[permissions]
	#Sollte der Kolonie Schutz aktiviert sein? [Standard: true]
	enablecolonyprotection = true
	#Sollten unabhängig vom Kolonie Schutz Explosionen innerhalb von Kolonien ausgeschaltet werden? DAMAGE_NOTHING verhindert Explosionen vollständig. DAMAGE_PLAYERS, erlaubt Explosionen, Spieler und feindliche Mobs zu beschädigen, aber nicht Blöcke oder neutrale oder freundliche Mobs. DAMAGE_ENTITIES erlaubt Schaden an allen Entitäten. DAMAGE_EVERYTHING lässt Explosionen zu, die Entitäten und Blöcke beschädigen. 
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_EVERYTHING"
	#Blöcke, mit denen jeder Spieler in jeder Kolonie interagieren kann 
	freetointeractblocks = ["dirt", "0 0 0"]

#Alle Konfigurationen bezüglich Mod Kompatibilität
[compatibility]
	#Gegenstände, die von Bürgern in der Bibliothek konsumiert werden. 
	configliststudyitems = ["minecraft:paper;400;100", "minecraft:book;600;10"]
	#Gegenstände, die von Tavernen-Besuchern angefordert werden. 
	configlistrecruitmentitems = ["minecraft:hay_block;3", "minecraft:book;2", "minecraft:enchanted_book;9", "minecraft:diamond;9", "minecraft:emerald;8", "minecraft:baked_potato;1", "minecraft:gold_ingot;2", "minecraft:redstone;2", "minecraft:lapis_lazuli;2", "minecraft:cake;11", "minecraft:sunflower;5", "minecraft:honeycomb;6", "minecraft:quartz;3"]
	#Liste der Erze die der Bergarbeiter auf magische weise Finden kann (siehe "Erz Wahrscheinlichkeit") Beinhaltet den Block und seine Wahrscheinlichkeit, separiert durch Ausrufezeichen. 
	luckyores = ["minecraft:coal_ore!64", "minecraft:copper_ore!48", "minecraft:iron_ore!32", "minecraft:gold_ore!16", "minecraft:redstone_ore!8", "minecraft:lapis_ore!4", "minecraft:diamond_ore!2", "minecraft:emerald_ore!1"]
	#Alle Krankheiten die Bewohner bekommen können. Der Name, wie gewöhnlich Sie ist, und alle Zutaten um es zu heilen. 
	diseases = ["Influenza,100,minecraft:carrot,minecraft:potato", "Measles,10,minecraft:dandelion,minecraft:kelp,minecraft:poppy", "Smallpox,1,minecraft:honey_bottle,minecraft:golden_apple"]
	#Beim Laden von Rezepten werden Revisions-CSV-Dateien erstellt, um die Fehlersuche bei Datapacks oder zusätzlichen Mods zu erleichtern. [Standard: false]
	auditcraftingtags = false
	#Schalte debuggen des Inventars ein. [Standard: false]
	debuginventories = false
	#Schalte dies ein, wenn du diese Welt zum Bauen und Scannen von Blaupausen verwendest. [Standard: false]
	blueprintbuildmode = false

#Alle Einstellungen für "Weg finden"
[pathfinding]
	#Die Genauigkeit der Wegfindungsdebugnachrichten. [Standard: 0, min: 0, max: 10]
	#Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#Mindeste aufeinanderfolgende Schienen für Bewohner. [Standard: 8, min: 5, max: 100]
	#Range: 5 ~ 100
	minimumrailstopath = 8
	#Anzahl der zusätzlichen Wege die für die Weg Findung berechnet werden [Standard: 2, min: 1, max: 10]
	#Range: 1 ~ 10
	pathfindingmaxthreadcount = 2

#Alle Konfigurationen beziehen sich auf das Anforderungssystem
[requestSystem]
	#Sollte das Anfragesystem (wenn möglich) kreativ lösen, wenn der Spieler eine Anfrage lösen muss? Dies ist ein Debugging-Tool und kann sehr lange dauern, um eine Anfrage zu lösen. [Standard: false]
	creativeresolve = false

