
#Alle Konfigurationen zu Kernfunktionen des Spiels
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment [Standard: true]
	enablecitizenvoices = true
	#Wenn Sie einen Schaltplan in der Nähe anderer Gebäude platzieren, werden die bereits platzierten Gebäude standardmäßig so dargestellt, als ob sie sich auf Stufe 5 befänden, und mit einem blauen Umriss versehen. Sie können dies deaktivieren, indem Sie diese Option auf false setzen. [Standard: true]
	neighborbuildingrendering = true
	#"Wie nah ein Gebäude an einem anderen sein muss, um als Nachbar zu gelten, in Blöcken. -1 = sich überschneidend, 0 = berührend" [Standard: 4, min: -2, max: 16]
	#Range: -2 ~ 16
	neighborbuildingrange = 4
	#So nah (in Blöcken) muss man sein, um beim Tragen einer Bauarbeiterbrille die Arbeitsaufträge zu sehen. [Standard: 50, min: 1, max: 250]
	#Range: 1 ~ 250
	buildgogglerange = 50
	#Wenn es wahr ist, werden die Grenzen der Kolonie in der Teamfarbe der Kolonie angezeigt, wenn das Bauwerkzeug gehalten wird. Wenn es falsch ist, wird die Kolonie, in der du dich befindest, weiß und alle anderen Kolonien werden rot sein. [Standard: true]
	colonyteamborders = true

